name: CI Workflow

on:
  push:
    branches:
      - master  # or "main" based on your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say hello
        run: echo "✅ GitHub Action is running successfully!"

